
on:
  push:
    paths:
      - config/corneish_zen.conf
      - config/corneish_zen.keymap
  pull_request:
    paths:
      - config/corneish_zen.conf
      - config/corneish_zen.keymap
  workflow_dispatch: {}

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
